2022.0215/v2.1.135
- Minor change: remove duplicate test_0_mostviewed_argument_robustness which was in two test files.
- Separate out opasPySolrLib functions used by opasSiteMap; there seems to be a problem with imports (perhaps circularity?). When the caches use opasPySolrLib functions for search we get load errors: 2022-02-14 21:14:12 opasWhatsNewCache/load_whats_new(37): ERROR Error in database_whatsnew: module 'opasPySolrLib' has no attribute 'database_get_whats_new'. Raising HTTP_400_BAD_REQUEST.
2022-02-14 21:14:12 opasCacheMostViewed/load_most_viewed(48): ERROR MostViewedError: Exception: module 'opasPySolrLib' has no attribute 'document_get_most_viewed'

In this build, those are moved to new files:
- opasCacheSupport now holds document_get_most_viewed
- opasPySolrSearch now holds copies of the search functions from opasPySolrLib which were failing to load in the independent opasSiteMap.

But they are still in opasPySolrLib for now, and used by the opasServer (e.g., main.py there.

Next version will try those in the new location from the main, as long as the load problems (if from circularities) don't return.